/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game.view;

import java.awt.event.KeyEvent;
import game.model.ModelObject;
import game.control.Controller;
import game.model.Player;
import java.awt.Dimension;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import javax.swing.JTextArea;

/**
 *
 * @author andrej
 */
public class GameView extends javax.swing.JFrame {

    int directionX, directionY;
    //public boolean shooting = false;
    private Controller controller;
    
    /**
     * Creates new form gameView
     */
    public GameView(Controller controller) {
        initComponents();
        this.controller = controller;
        controller.setView(this);
        this.requestFocus();
        //this.setResizable(false);
    }
    
    
    public void updateModel(List<ModelObject> model) {
        mainPanel.updateModel(model);
    }
    
    public void finishGameMessage() {
        
        JOptionPane.showMessageDialog(null, "Prehrali ste.");
        
    }
    
    public void startGameMessage() {
        
        JOptionPane.showMessageDialog(null, "Vitajte v hre.");
    }
    
    public void cannotConnectMessage() {
        JOptionPane.showMessageDialog(null, "Neda sa pripojiť k serveru.");
    }
    
    public int getDirectionX() {
        return directionX;
    }

    public int getDirectionY() {
        return directionY;
    }
    
    public void debugText(String string) {
        String text = textArea.getText();
        textArea.setText(text + "\n" + string);
    }
    
    
    public String playersNameSelectDialog() {

        String s = (String) JOptionPane.showInputDialog(
                null,
                "Type your player name:"
        );

        //If a string was returned, say so.
        if ((s != null) && (s.length() > 0)) {

            return s;
        }
        else {
            playersNameSelectDialog();
        }
        
        return "";
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startButton = new javax.swing.JButton();
        mainPanel = new game.view.MainPanel();
        StopButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        gameNameLabel = new javax.swing.JLabel();
        sendToServerInput = new javax.swing.JTextField();
        sendToServer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 500));
        setPreferredSize(new java.awt.Dimension(800, 700));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        mainPanel.setMaximumSize(new java.awt.Dimension(1900, 1900));
        mainPanel.setMinimumSize(new java.awt.Dimension(600, 400));
        mainPanel.setPreferredSize(new java.awt.Dimension(600, 400));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 637, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 634, Short.MAX_VALUE)
        );

        StopButton.setText("Stop");
        StopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopButtonActionPerformed(evt);
            }
        });

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        gameNameLabel.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        gameNameLabel.setText("Multiplayer");

        sendToServerInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendToServerInputActionPerformed(evt);
            }
        });

        sendToServer.setText("Send");
        sendToServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendToServerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(gameNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startButton)
                .addGap(18, 18, 18)
                .addComponent(StopButton)
                .addGap(31, 31, 31)
                .addComponent(sendToServerInput, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sendToServer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(gameNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(startButton)
                        .addComponent(StopButton)
                        .addComponent(sendToServerInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sendToServer)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        controller.start();
        textArea.setText("Hra sa zacala !");
        this.requestFocus();
    }//GEN-LAST:event_startButtonActionPerformed
    
    public Dimension getPanelSize() {
        return mainPanel.getSize();
    }
    
    
    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        
        //System.out.println(evt.getKeyCode());
        
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_LEFT:
                directionX = - Player.PLAYER_MOVE_OFFSET;
                controller.moving = true;
                break;
            case KeyEvent.VK_RIGHT:
                directionX = Player.PLAYER_MOVE_OFFSET;
                controller.moving = true;
                break;
            case KeyEvent.VK_UP:
                //System.out.println("KEY PRESSED\n");
                directionY = - Player.PLAYER_MOVE_OFFSET;
                controller.moving = true;
                break;
            case KeyEvent.VK_DOWN:
                directionY = Player.PLAYER_MOVE_OFFSET;
                controller.moving = true;
                break;
            case 32:                                    //space
                //System.out.println("SHOOOOOTING");        
                //shooting = true;
                break;
            default:
        }
    }//GEN-LAST:event_formKeyPressed

    
    
    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_LEFT:
                directionX = 0;
                break;
            case KeyEvent.VK_RIGHT:
                directionX = 0;
                break;
            case KeyEvent.VK_UP:
                directionY = 0;
                break;
            case KeyEvent.VK_DOWN:
                directionY = 0;
                break;
            default:
        }
    }//GEN-LAST:event_formKeyReleased

    
    
    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyTyped

    
    
    private void StopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopButtonActionPerformed
        controller.stop();
        this.requestFocus();
    }//GEN-LAST:event_StopButtonActionPerformed

    private void sendToServerInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendToServerInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sendToServerInputActionPerformed

    private void sendToServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendToServerActionPerformed
        
        String in = this.sendToServerInput.getText();
        System.out.println("Sending message: " + in);
        controller.client.sendMessage(in);

    }//GEN-LAST:event_sendToServerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
       /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameView().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton StopButton;
    private javax.swing.JLabel gameNameLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private game.view.MainPanel mainPanel;
    private javax.swing.JButton sendToServer;
    private javax.swing.JTextField sendToServerInput;
    private javax.swing.JButton startButton;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
